<Project>
  <PropertyGroup>
    <!-- Central app version: change ONLY here to update all platform projects -->
    <IgVersion>10.0.2.630</IgVersion>
    <IgReleaseType>beta-2</IgReleaseType>
    <IgUpdateChannel>beta</IgUpdateChannel>

    <!-- App bundle version. Leave empty to derive from IgVersion -->
    <IgBundleShortVersion>10.0.2</IgBundleShortVersion>
    <IgBundleBuild>535</IgBundleBuild>
  </PropertyGroup>
</Project>
